"""add skills and experience skill links

Revision ID: 0148a2e48f6f
Revises: a6e21ce475ec
Create Date: 2026-07-26 15:32:24.199386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0148a2e48f6f'
down_revision: Union[str, Sequence[str], None] = 'a6e21ce475ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Enum('beginner', 'developing', 'proficient', 'advanced', name='proficiency_level'), nullable=False),
    sa.Column('development_goal', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'name', name='uq_skill_student_name')
    )
    op.create_index(op.f('ix_skills_student_id'), 'skills', ['student_id'], unique=False)
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('experience_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experience_skills')
    op.drop_index(op.f('ix_skills_student_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
