"""add career tasks

Revision ID: 342b53477bc5
Revises: 1ede50a5ca18
Create Date: 2026-07-28 10:04:32.153587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '342b53477bc5'
down_revision: Union[str, Sequence[str], None] = '1ede50a5ca18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.Enum('resume', 'cover_letter', 'linkedin', 'interview', 'networking', 'application', 'career_advising', 'portfolio', 'skill_development', 'other', name='career_task_category'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='career_task_priority'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_tasks_student_id'), 'career_tasks', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_tasks_student_id'), table_name='career_tasks')
    op.drop_table('career_tasks')
    # ### end Alembic commands ###
